import { Inter } from "next/font/google";
import "@/css/globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Welcome to Namaz Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="forest" lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
